### ISSUE TITLE
Why is the release of this application taking sooo long??

### ISSUE THREAD

**Issue by toreylittlefield** [zainafzal88/scrumblr-enhancement#27]
![vector-illustration-of-cartoon-wild-boar-G38DKM](https://user-images.githubusercontent.com/52614742/136547145-9833c6d7-7c46-4d26-80ba-766b9568538d.jpg)

**Comment by zainafzal88** [comment]
Because we are not working on it full time lol!!

**Comment by andreigec** [comment]
![image](https://user-images.githubusercontent.com/1860848/178489186-fc90595c-2009-4d4c-90a3-53007f644c37.png)
