### ISSUE TITLE
Migrate Scrumblr frontend to S3

### ISSUE THREAD

**Issue by zainafzal88** [zainafzal88/scrumblr-enhancement#3]
Copy Scrumblr front-end files & folders to AWS S3

**Comment by drumovski** [comment]
Successfully uploaded scrumblr front end files to both AWS s3 and localstack emulating aws s3.
Pictured is a screenshot of the localstack s3 home.html
![Screenshot from 2021-06-06 20-57-21](https://user-images.githubusercontent.com/15879963/120922029-410e7900-c70a-11eb-84cf-1f690e2506cc.png)

**Comment by zainafzal88** [comment]
@drumovski Looking good. Well done!
